/* Generated By:JavaCC: Do not edit this line. JavaCCParserConstants.java */
package jminusminus;

public interface JavaCCParserConstants {

  int EOF = 0;
  int SINGLE_LINE_COMMENT = 6;
  int ABSTRACT = 10;
  int BOOLEAN = 11;
  int CHAR = 12;
  int CLASS = 13;
  int ELSE = 14;
  int EXTENDS = 15;
  int FALSE = 16;
  int IF = 17;
  int IMPORT = 18;
  int INSTANCEOF = 19;
  int INT = 20;
  int NEW = 21;
  int NULL = 22;
  int PACKAGE = 23;
  int PRIVATE = 24;
  int PROTECTED = 25;
  int PUBLIC = 26;
  int RETURN = 27;
  int STATIC = 28;
  int SUPER = 29;
  int THIS = 30;
  int TRUE = 31;
  int VOID = 32;
  int WHILE = 33;
  int PLUS = 34;
  int ASSIGN = 35;
  int DEC = 36;
  int EQUAL = 37;
  int GT = 38;
  int INC = 39;
  int LAND = 40;
  int LOR = 41;
  int LE = 42;
  int LNOT = 43;
  int MINUS = 44;
  int PLUS_ASSIGN = 45;
  int STAR = 46;
  int LPAREN = 47;
  int RPAREN = 48;
  int LCURLY = 49;
  int RCURLY = 50;
  int LBRACK = 51;
  int RBRACK = 52;
  int SEMI = 53;
  int COMMA = 54;
  int DOT = 55;
  int IDENTIFIER = 56;
  int LETTER = 57;
  int DIGIT = 58;
  int NON_ZERO_DIGIT = 59;
  int INT_LITERAL = 60;
  int CHAR_LITERAL = 61;
  int STRING_LITERAL = 62;
  int ESC = 63;
  int ERROR = 64;

  int DEFAULT = 0;
  int IN_MULTI_LINE_COMMENT = 1;

  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "\"\\f\"",
    "<SINGLE_LINE_COMMENT>",
    "\"/*\"",
    "\"*/\"",
    "<token of kind 9>",
    "\"abstract\"",
    "\"boolean\"",
    "\"char\"",
    "\"class\"",
    "\"else\"",
    "\"extends\"",
    "\"false\"",
    "\"if\"",
    "\"import\"",
    "\"instanceof\"",
    "\"int\"",
    "\"new\"",
    "\"null\"",
    "\"package\"",
    "\"private\"",
    "\"protected\"",
    "\"public\"",
    "\"return\"",
    "\"static\"",
    "\"super\"",
    "\"this\"",
    "\"true\"",
    "\"void\"",
    "\"while\"",
    "\"+\"",
    "\"=\"",
    "\"--\"",
    "\"==\"",
    "\">\"",
    "\"++\"",
    "\"&&\"",
    "\"||\"",
    "\"<=\"",
    "\"!\"",
    "\"-\"",
    "\"+=\"",
    "\"*\"",
    "\"(\"",
    "\")\"",
    "\"{\"",
    "\"}\"",
    "\"[\"",
    "\"]\"",
    "\";\"",
    "\",\"",
    "\".\"",
    "<IDENTIFIER>",
    "<LETTER>",
    "<DIGIT>",
    "<NON_ZERO_DIGIT>",
    "<INT_LITERAL>",
    "<CHAR_LITERAL>",
    "<STRING_LITERAL>",
    "<ESC>",
    "<ERROR>",
  };

}
